---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: hin-tanzu-spring-app
    apps.tanzu.vmware.com/workload-type: web
  name: hin-tanzu-spring-app
spec:
  source:
    git:
      ref:
        branch: main
      url: github.com/hinyinlam/hin-tanzu-spring-app
status:
  supplyChainRef: {}
